### PR TITLE
updated node and angular/cli to match pom.xml

### PR DESCRIPTION
**Pull request by andy-scollard**

### CODE REVIEW

**Comment by Sbrenthughes** [comment]
Thanks for the PR. Can you make that you have signed the contributor agreement? https://hygieia.github.io/Hygieia/contribute.html

**Comment by andy-scollard** [comment]
I signed this on monday and still haven't seen any movement on the PR.
Yesterday I added another change, this time on gitlab scm collector. When
will these be implemented or discarded? FYI, I work with Prem Yadav from
T-Mobile. We have calls with your team on a regular basis and are about to
start pushing a bunch of pull requests for work we have done on a number of
items, although I go on PTO at the end of the month so I'm not sure we get
them all out of the way until September.

-Andy-

**Comment by rvema** [comment]
@andy-scollard We will get this change accepted very shortly

**Comment by Sbrenthughes** [comment]
@andy-scollard Thank you for the contribution. We appreciate your patience as this UI is a WIP repo that is no longer the top priority. As such other PRs on different repos will be looked at first.

**Pull request merged**
